# Play to setup GNS3 project and nodes, it retrieves their console information
- hosts: localhost
  gather_facts: no
  vars_files:
    - /taf/etc/1_gns3_vars.yml
  collections:
    - davidban77.gns3

  tasks:
    - name: Get server version
      gns3_facts:
         url: "{{ gns3_url }}"
         get_images: all
         get_compute_ports: yes
      register: resultado
 
    - debug: var=resultado



    - name: Lab creation and setup
      block:
#        - name: Get server version
#          gns3_facts:
#            url: "{{ gns3_url }}"
#            get_images: all
#            get_compute_ports: yes
#          register: resultado

#        - debug: var=resultado

        - import_role:
            name: create_lab

        - name: Collect the nodes inventory
          gns3_nodes_inventory:
            url: "{{ gns3_url }}"
            project_name: "{{ gns3_project_name }}"
          register: nodes_inventory

        - name: Print Nodes Inventory Info
          debug: var=nodes_inventory

    - name: Pause section
      when: boilerplate.config == "deploy" and boilerplate.automated_push == "no"
      pause:
        prompt: "Press Enter to proceed with configuration deployments:"

    - name: Pause section
      when: boilerplate.config == "deploy" and boilerplate.automated_push == "yes"
      pause:
        minutes: "{{ boilerplate.automated_push_delay | default(4) }}"

# Play that goes through the inventory devices to generate/push boiler plate config


- hosts: all
  gather_facts: no
  vars:
     ansible_connection: local
     ansible_python_interpreter: "{{ansible_playbook_python}}"
  vars_files:
    - /taf/etc/1_gns3_vars.yml
  collections:
    - davidban77.gns3

  tasks:
    - name: Retrieving nodes inventory information
      set_fact:
        nodes_inventory: "{{ hostvars['localhost']['nodes_inventory']['nodes_inventory'] }}"
  
    - name: Print Host Info
      debug: var=nodes_inventory

    - name: print host net os
      debug:  var=ansible_net_os

    - name: Generate boilerplate config files
      when: boilerplate.config == "generate" and ansible_net_os != "gns3_builtin"
      block:
        - name: Create build folder
          file:
            path: "{{ playbook_dir }}/build"
            state: directory

        - name: Generate config
          template:
            src: /taf/etc/templates/1_{{ ansible_net_os }}_template.j2
            dest: "{{ playbook_dir }}/build/{{ inventory_hostname }}-{{ ansible_net_os }}.conf"

    - name: Deploy boilerplate configuration
      when: boilerplate.config == "deploy" and ansible_net_os != "gns3_builtin"
      block:
        - name: Generate configuration variable
          set_fact:
            boilerplate_config: "{{ lookup('template', '/taf/etc/1_{{ ansible_net_os }}_template.j2') }}"

        - name: print network template result
          debug: var=boilerplate_config

        - name: "Push config"
          when: ansible_net_os == "ios" and image_style == "iosv_l2"
          gns3_telnet_console:
            remote_addr: "{{ nodes_inventory[inventory_hostname]['server'] }}"
            port: "{{ nodes_inventory[inventory_hostname]['console_port'] }}"
            send_newline: yes
            login_prompt:
              - ">"
            user: ""
            password: ""
            prompts:
              - "[#]"
            command: "{{ boilerplate_config.splitlines() }}"
            pause: 1
            timeout:
              general: 90
              pre_login: 60
              post_login: 60
              login_prompt: 30
              config_dialog: 30

        - name: "Push config"
          when: ansible_net_os == "ios" and image_style == "iosv_l3"
          gns3_telnet_console:
            remote_addr: "{{ nodes_inventory[inventory_hostname]['server'] }}"
            port: "{{ nodes_inventory[inventory_hostname]['console_port'] }}"
            send_newline: yes
            command: "{{ boilerplate_config.splitlines() }}"
            pause: 1
            timeout:
              general: 90
              pre_login: 60
              post_login: 60
              login_prompt: 30
              config_dialog: 30

